services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./prisma/data:/var/lib/postgresql/data
volumes:
  prisma:
    driver: local
